spring:
  application:
    name: eurekaserver
  profiles:    active:    - local  
  security:
   basic:
    enabled: true
   user:      name: eureka
      password: eureka
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false